name: "Validate Gradle Wrapper"
on: [commit, push, pull_request]

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: build
        run: build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: jellyfin-test
          path: bin
      
